"""Export findings to JSON / CSV / PDF with full provenance and the verdict
reason-trail. Every claim is traceable — no black-box conclusions.
"""

from __future__ import annotations

import csv
import html
import io
import json
from datetime import datetime, timezone
from pathlib import Path

from .config import SETTINGS
from .evidence import confirmation_satisfied
from .models import Finding, Query

DISCLAIMER = (
    "Generated by Specter for authorized research / educational use only. "
    "Findings use source-specific deterministic verification and explicit evidence "
    "policies. FOUND confirms the stated observation, not identity ownership. "
    "UNCERTAIN entries are unconfirmed."
)


def _payload(query, findings: list[Finding], summary: dict) -> dict:
    from .provenance import provenance

    return {
        "tool": "Specter",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "provenance": provenance(),
        "query": query.model_dump(exclude_none=True),
        "disclaimer": DISCLAIMER,
        "summary": summary,
        "findings": [f.model_dump() for f in findings],
    }


def to_json(query, findings, summary) -> str:
    return json.dumps(_payload(query, findings, summary), indent=2, default=str)


def to_csv(findings: list[Finding]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(
        [
            "verdict",
            "confidence",
            "category",
            "source",
            "label",
            "url",
            "reasons",
            "origin",
            "evidence_class",
            "observed_at",
            "completeness",
        ]
    )
    for f in findings:
        w.writerow(
            [
                _csv_cell(value)
                for value in (
                    f.verdict.value,
                    f.confidence,
                    f.category,
                    f.source,
                    f.label,
                    f.url or "",
                    " | ".join(f.reasons),
                    f.origin.origin if f.origin else "",
                    f.origin.evidence_class.value if f.origin else "",
                    f.temporal.observed_at.isoformat() if f.temporal.observed_at else "",
                    f.completeness.value,
                )
            ]
        )
    return buf.getvalue()


def _csv_cell(value) -> str:
    """Prevent spreadsheet formula execution when exported OSINT text is opened."""
    text = str(value)
    if text.lstrip().startswith(("=", "+", "-", "@")):
        return "'" + text
    return text


def _profile_html(profile: dict | None) -> str:
    if not profile:
        return ""
    identifiers = "".join(
        "<tr>"
        f"<td>{html.escape(str(row.get('type', '')))}</td>"
        f"<td>{html.escape(str(row.get('value', '')))}</td>"
        f"<td>{html.escape(str(row.get('standing', '')))}</td>"
        f"<td>{float(row.get('confidence') or 0):.2f}</td>"
        "</tr>"
        for row in profile.get("identifiers", [])
    )
    accounts = "".join(
        "<li>"
        f"{html.escape(str(row.get('label', '')))} — "
        f"{html.escape(str(row.get('standing', '')))}"
        + (f" — {html.escape(str(row.get('url')))}" if row.get("url") else "")
        + "</li>"
        for row in profile.get("accounts", [])
    )
    gaps = "".join(f"<li>{html.escape(str(item))}</li>" for item in profile.get("gaps", []))
    phone = profile.get("phone_research") or {}
    allocation = "".join(
        f"<tr><td>{html.escape(str(key).replace('_', ' '))}</td>"
        f"<td>{html.escape(str(value))}</td></tr>"
        for key, value in (phone.get("allocation") or {}).items()
    )
    identity_links = "".join(
        f"<li>{html.escape(str(row.get('type', '')))}: "
        f"{html.escape(str(row.get('value', '')))} — "
        f"{html.escape(str(row.get('standing', 'candidate')))} "
        f"({int(row.get('independent_origins') or 0)} independent origin(s))</li>"
        for row in phone.get("identity_links", [])
    )
    mentions = "".join(
        f"<li>{html.escape(str(row.get('title') or row.get('domain') or 'Public mention'))}"
        f" — {html.escape(str(row.get('association', 'unresolved mention')).replace('_', ' '))}"
        + (f" — {html.escape(str(row.get('url')))}" if row.get("url") else "")
        + "</li>"
        for row in phone.get("mentions", [])
    )
    decision = phone.get("decision") or {}
    phone_html = ""
    if phone:
        lifecycle = phone.get("lifecycle") or {}
        phone_html = (
            "<h3>Phone research</h3>"
            f"<p><b>{html.escape(str(phone.get('number', 'Number dossier')))}</b> — "
            f"{html.escape(str(lifecycle.get('state', 'unresolved')).replace('_', ' '))}</p>"
            f"<p>{html.escape(str(phone.get('ownership_note', '')))}</p>"
            f"<p><b>Next justified step:</b> "
            f"{html.escape(str(decision.get('recommended_action', 'No automatic continuation.')))}</p>"
            "<h4>Numbering plan</h4><table><tr><th>Field</th><th>Value</th></tr>"
            f"{allocation}</table>"
            f"<p><small>{html.escape(str(phone.get('allocation_note', '')))}</small></p>"
            f"<h4>Identity links</h4><ul>{identity_links or '<li>None corroborated.</li>'}</ul>"
            f"<h4>Direct public mentions</h4><ul>{mentions or '<li>None observed.</li>'}</ul>"
        )
    return (
        "<h2>Profile synthesis</h2>"
        f"<p><b>{html.escape(str(profile.get('title', 'Profile')))}</b> — "
        f"{html.escape(str(profile.get('status', 'unresolved')))} — "
        f"{float(profile.get('confidence') or 0):.0%} evidence confidence</p>"
        f"<p>{html.escape(str(profile.get('assessment', '')))}</p>"
        "<h3>Identifiers</h3>"
        "<table><tr><th>Type</th><th>Value</th><th>Standing</th><th>Confidence</th></tr>"
        f"{identifiers}</table>"
        f"<h3>Public accounts</h3><ul>{accounts or '<li>No association corroborated.</li>'}</ul>"
        f"{phone_html}"
        f"<h3>Unresolved gaps</h3><ul>{gaps or '<li>None recorded.</li>'}</ul>"
        f"<p><small>{html.escape(str(profile.get('completeness_note', '')))}</small></p>"
    )


def to_pdf_html(query, findings, summary) -> str:
    """HTML used for PDF rendering (weasyprint) — also a standalone report."""
    rows = "".join(
        f"<tr class='{f.verdict.value}'><td>{f.verdict.value}</td>"
        f"<td>{f.confidence:.2f}</td><td>{html.escape(f.source)}</td>"
        f"<td>{html.escape(f.label)}</td>"
        f"<td>{'<br>'.join(html.escape(reason) for reason in f.reasons)}"
        + (
            f"<br><small>{html.escape(f.origin.evidence_class.value)} · "
            f"{html.escape(f.origin.origin)} · {html.escape(f.completeness.value)}</small>"
            if f.origin
            else ""
        )
        + "</td></tr>"
        for f in findings
        if f.is_notable
    )
    query_json = html.escape(json.dumps(query.model_dump(exclude_none=True)))
    profile_html = _profile_html(summary.get("profile"))
    summary_json = html.escape(
        json.dumps(
            {key: value for key, value in summary.items() if key != "profile"},
            indent=2,
            default=str,
        )
    )
    disclaimer = html.escape(DISCLAIMER)
    return f"""<html><head><meta charset='utf-8'><style>
    body{{font:12px sans-serif}} table{{border-collapse:collapse;width:100%}}
    td,th{{border:1px solid #ccc;padding:4px;text-align:left;vertical-align:top}}
    .FOUND{{background:#eafaef}} .UNCERTAIN{{background:#fdf6e3}}
    </style></head><body>
    <h1>Specter report</h1>
    <p><b>Query:</b> {query_json}</p>
    <p><small>{disclaimer}</small></p>
    {profile_html}
    <h2>Notable findings</h2>
    <table><tr><th>Verdict</th><th>Conf</th><th>Source</th><th>Label</th><th>Reasons</th></tr>
    {rows}</table>
    <h2>Summary</h2><pre>{summary_json}</pre>
    </body></html>"""


def entity_report(run_id: int) -> dict:
    """Entity-centric report for a stored run: identities, their corroborating
    observations (with provenance), and changes since the prior run."""
    from .store import get_db, repo
    from .store import models_db as m

    db = get_db()
    with db.session() as s:
        run = s.get(m.Run, run_id)
        if not run:
            raise ValueError(f"no such run: {run_id}")
        target = s.get(m.Target, run.target_id)
        query = Query.model_validate(target.query)
        entities = repo.list_entities(s, run.target_id)
        changes = repo.list_changes(s, target_id=run.target_id)
        contradictions = repo.contradictions_for_target(s, run.target_id)
        from .provenance import provenance

        return {
            "tool": "Specter",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "provenance": provenance(),
            "run_id": run_id,
            "target": {"id": target.id, "label": target.label, "query": target.query},
            "disclaimer": DISCLAIMER,
            "profile": (run.stats or {}).get("profile"),
            "identities": [
                {
                    "id": e.id,
                    "label": e.label,
                    "confidence": e.confidence,
                    "flags": e.flags,
                    "attributes": e.attributes,
                    "evidence": [
                        {
                            "source": o.source,
                            "label": o.label,
                            "url": o.url,
                            "verdict": o.verdict,
                            "confidence": o.confidence,
                            "reliability": o.reliability,
                            "reasons": o.reasons,
                            "origin": o.origin,
                            "evidence_class": o.evidence_class,
                            "independence_key": o.independence_key,
                            "extractions": o.extractions or [],
                            "confidence_dimensions": o.confidence_dimensions,
                            "temporal_status": o.temporal_status,
                            "observed_at": o.observed_at.isoformat() if o.observed_at else None,
                            "first_seen_at": (
                                o.first_seen_at.isoformat() if o.first_seen_at else None
                            ),
                            "last_seen_at": o.last_seen_at.isoformat() if o.last_seen_at else None,
                            "completeness": o.completeness,
                        }
                        for o in e.observations
                        if confirmation_satisfied(o, e.observations, query)
                    ],
                }
                for e in entities
            ],
            "changes": [
                {
                    "kind": c.kind,
                    "source": c.source,
                    "label": c.label,
                    "detail": c.detail,
                    "at": c.created_at.isoformat(),
                }
                for c in changes
            ],
            "contradictions": [
                {
                    "id": c.id,
                    "claim_key": c.claim_key,
                    "earlier_observation_id": c.earlier_observation_id,
                    "later_observation_id": c.later_observation_id,
                    "kind": c.kind,
                    "severity": c.severity,
                    "reasons": c.reasons,
                    "at": c.created_at.isoformat(),
                }
                for c in contradictions
            ],
        }


def save(query, findings, summary, fmt: str, out: str | None = None) -> Path:
    reports = Path(SETTINGS.reports_dir)
    reports.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    path = Path(out) if out else reports / f"specter-{stamp}.{fmt}"

    if fmt == "json":
        path.write_text(to_json(query, findings, summary), encoding="utf-8")
    elif fmt == "csv":
        path.write_text(to_csv(findings), encoding="utf-8")
    elif fmt == "pdf":
        html = to_pdf_html(query, findings, summary)
        try:
            from weasyprint import HTML  # optional dependency

            HTML(string=html).write_pdf(str(path))
        except Exception:
            path = path.with_suffix(".html")
            path.write_text(html, encoding="utf-8")
    else:
        raise ValueError(f"unknown format: {fmt}")
    return path
