"""Export findings to JSON / CSV / PDF with full provenance and the verdict
reason-trail. Every claim is traceable — no black-box conclusions.
"""

from __future__ import annotations

import csv
import html
import io
import json
from datetime import datetime, timezone
from pathlib import Path

from .config import SETTINGS
from .evidence import confirmation_satisfied
from .models import Finding, Query, Verdict

DISCLAIMER = (
    "Generated by Specter for authorized research / educational use only. "
    "Findings use source-specific deterministic verification and explicit evidence "
    "policies. FOUND confirms the stated observation, not identity ownership. "
    "UNCERTAIN entries are unconfirmed."
)


def _payload(query, findings: list[Finding], summary: dict) -> dict:
    from .provenance import provenance

    return {
        "tool": "Specter",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "provenance": provenance(),
        "query": query.model_dump(exclude_none=True),
        "disclaimer": DISCLAIMER,
        "summary": summary,
        "findings": [f.model_dump() for f in findings],
    }


def to_json(query, findings, summary) -> str:
    return json.dumps(_payload(query, findings, summary), indent=2, default=str)


def to_csv(findings: list[Finding]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(
        [
            "verdict",
            "confidence",
            "category",
            "source",
            "label",
            "url",
            "reasons",
            "origin",
            "evidence_class",
            "observed_at",
            "completeness",
            "independence_key",
            "content_sha256",
        ]
    )
    for f in findings:
        w.writerow(
            [
                _csv_cell(value)
                for value in (
                    f.verdict.value,
                    f.confidence,
                    f.category,
                    f.source,
                    f.label,
                    f.url or "",
                    " | ".join(f.reasons),
                    f.origin.origin if f.origin else "",
                    f.origin.evidence_class.value if f.origin else "",
                    f.temporal.observed_at.isoformat() if f.temporal.observed_at else "",
                    f.completeness.value,
                    f.origin.independence_key if f.origin else "",
                    ((f.trace or {}).get("request") or {}).get("content_sha256", ""),
                )
            ]
        )
    return buf.getvalue()


def finding_from_observation(observation) -> Finding:
    """Rehydrate persisted evidence for report generation without losing lineage."""
    origin = None
    if observation.collector and observation.origin and observation.independence_key:
        origin = {
            "collector": observation.collector,
            "operator": observation.origin,
            "origin": observation.origin,
            "evidence_class": observation.evidence_class or "unknown",
            "independence_key": observation.independence_key,
        }
    return Finding.model_validate({
        "source": observation.source,
        "category": observation.category,
        "label": observation.label,
        "url": observation.url,
        "verdict": observation.verdict,
        "confidence": observation.confidence,
        "reasons": observation.reasons or [],
        "breakdown": observation.breakdown,
        "trace": observation.trace,
        "signals": observation.signals or {},
        "data": observation.data or {},
        "origin": origin,
        "extractions": observation.extractions or [],
        "temporal": {
            "observed_at": observation.observed_at,
            "valid_from": observation.valid_from,
            "valid_until": observation.valid_until,
            "first_seen_at": observation.first_seen_at,
            "last_seen_at": observation.last_seen_at,
            "status": observation.temporal_status or "unknown",
        },
        "completeness": observation.completeness or "unknown",
        "confidence_dimensions": observation.confidence_dimensions,
        "policy": observation.policy or {},
    })


def _csv_cell(value) -> str:
    """Prevent spreadsheet formula execution when exported OSINT text is opened."""
    text = str(value)
    if text.lstrip().startswith(("=", "+", "-", "@")):
        return "'" + text
    return text


def _profile_html(profile: dict | None) -> str:
    if not profile:
        return ""
    identifiers = "".join(
        "<tr>"
        f"<td>{html.escape(str(row.get('type', '')))}</td>"
        f"<td>{html.escape(str(row.get('value', '')))}</td>"
        f"<td>{html.escape(str(row.get('standing', '')))}</td>"
        f"<td>{float(row.get('confidence') or 0):.2f}</td>"
        "</tr>"
        for row in profile.get("identifiers", [])
    )
    accounts = "".join(
        "<li>"
        f"{html.escape(str(row.get('label', '')))} — "
        f"{html.escape(str(row.get('standing', '')))}"
        + (f" — {html.escape(str(row.get('url')))}" if row.get("url") else "")
        + "</li>"
        for row in profile.get("accounts", [])
    )
    gaps = "".join(f"<li>{html.escape(str(item))}</li>" for item in profile.get("gaps", []))
    phone = profile.get("phone_research") or {}
    allocation = "".join(
        f"<tr><td>{html.escape(str(key).replace('_', ' '))}</td>"
        f"<td>{html.escape(str(value))}</td></tr>"
        for key, value in (phone.get("allocation") or {}).items()
    )
    identity_links = "".join(
        f"<li>{html.escape(str(row.get('type', '')))}: "
        f"{html.escape(str(row.get('value', '')))} — "
        f"{html.escape(str(row.get('standing', 'candidate')))} "
        f"({int(row.get('independent_origins') or 0)} independent origin(s))</li>"
        for row in phone.get("identity_links", [])
    )
    mentions = "".join(
        f"<li>{html.escape(str(row.get('title') or row.get('domain') or 'Public mention'))}"
        f" — {html.escape(str(row.get('association', 'unresolved mention')).replace('_', ' '))}"
        + (f" — {html.escape(str(row.get('url')))}" if row.get("url") else "")
        + "</li>"
        for row in phone.get("mentions", [])
    )
    decision = phone.get("decision") or {}
    phone_html = ""
    if phone:
        lifecycle = phone.get("lifecycle") or {}
        phone_html = (
            "<h3>Phone research</h3>"
            f"<p><b>{html.escape(str(phone.get('number', 'Number dossier')))}</b> — "
            f"{html.escape(str(lifecycle.get('state', 'unresolved')).replace('_', ' '))}</p>"
            f"<p>{html.escape(str(phone.get('ownership_note', '')))}</p>"
            f"<p><b>Next justified step:</b> "
            f"{html.escape(str(decision.get('recommended_action', 'No automatic continuation.')))}</p>"
            "<h4>Numbering plan</h4><table><tr><th>Field</th><th>Value</th></tr>"
            f"{allocation}</table>"
            f"<p><small>{html.escape(str(phone.get('allocation_note', '')))}</small></p>"
            f"<h4>Identity links</h4><ul>{identity_links or '<li>None corroborated.</li>'}</ul>"
            f"<h4>Direct public mentions</h4><ul>{mentions or '<li>None observed.</li>'}</ul>"
        )
    return (
        "<h2>Profile synthesis</h2>"
        f"<p><b>{html.escape(str(profile.get('title', 'Profile')))}</b> — "
        f"{html.escape(str(profile.get('status', 'unresolved')))} — "
        f"{float(profile.get('confidence') or 0):.0%} evidence confidence</p>"
        f"<p>{html.escape(str(profile.get('assessment', '')))}</p>"
        "<h3>Identifiers</h3>"
        "<table><tr><th>Type</th><th>Value</th><th>Standing</th><th>Confidence</th></tr>"
        f"{identifiers}</table>"
        f"<h3>Public accounts</h3><ul>{accounts or '<li>No association corroborated.</li>'}</ul>"
        f"{phone_html}"
        f"<h3>Unresolved gaps</h3><ul>{gaps or '<li>None recorded.</li>'}</ul>"
        f"<p><small>{html.escape(str(profile.get('completeness_note', '')))}</small></p>"
    )


def _finding_rows(findings: list[Finding]) -> str:
    rows = []
    for finding in findings:
        observed = (
            finding.temporal.observed_at.isoformat()
            if finding.temporal.observed_at else "time not recorded"
        )
        evidence_class = (
            finding.origin.evidence_class.value if finding.origin else "unknown origin"
        )
        lineage = finding.origin.independence_key if finding.origin else "unknown"
        receipt = ((finding.trace or {}).get("request") or {}).get("content_sha256")
        receipt_text = f" · receipt {receipt[:12]}" if receipt else ""
        reasons = "<br>".join(html.escape(reason) for reason in finding.reasons)
        rows.append(
            f"<tr class='{finding.verdict.value}'><td><b>{html.escape(finding.label)}</b>"
            f"<br><small>{html.escape(finding.source)}</small></td>"
            f"<td><span class='verdict'>{html.escape(finding.verdict.value.replace('_', ' ').title())}</span>"
            f"<br><small>{finding.confidence:.0%} observation confidence</small></td>"
            f"<td>{reasons or 'No explanation recorded.'}"
            f"<br><small>{html.escape(evidence_class)} · {html.escape(observed)} · "
            f"lineage {html.escape(lineage)}{html.escape(receipt_text)}</small></td></tr>"
        )
    return "".join(rows)


def to_pdf_html(query, findings, summary) -> str:
    """Conclusion-first standalone report used directly or rendered to PDF."""
    from .provenance import provenance

    profile = summary.get("profile") or {}
    observed = [finding for finding in findings if finding.verdict == Verdict.FOUND]
    review = [
        finding for finding in findings
        if finding.verdict in {Verdict.UNCERTAIN, Verdict.UNVERIFIABLE}
    ]
    failed = sum(finding.verdict == Verdict.ERROR for finding in findings)
    absent = sum(finding.verdict == Verdict.NOT_FOUND for finding in findings)
    gaps = list(profile.get("gaps") or [])
    if failed:
        gaps.append(f"{failed} source check(s) failed and leave coverage incomplete.")
    if any(finding.verdict == Verdict.UNVERIFIABLE for finding in findings):
        gaps.append("One or more sources blocked collection, so absence cannot be inferred.")
    assessment = profile.get("assessment") or (
        "The research produced positive source observations, but no synthesized identity "
        "assessment was available."
        if observed else
        "The research did not produce a positive source observation."
    )
    limitations = "".join(f"<li>{html.escape(str(item))}</li>" for item in gaps)
    stamp = provenance()
    query_json = html.escape(json.dumps(query.model_dump(exclude_none=True), sort_keys=True))
    disclaimer = html.escape(DISCLAIMER)
    return f"""<!doctype html><html><head><meta charset='utf-8'><style>
    @page{{size:A4;margin:18mm}} body{{font:11px Arial,sans-serif;color:#18202a;line-height:1.45}}
    h1{{font-size:25px;margin:0 0 4px}} h2{{font-size:16px;margin:24px 0 8px;border-bottom:2px solid #18202a;padding-bottom:5px}}
    h3{{font-size:13px;margin:16px 0 6px}} h4{{margin:12px 0 4px}} p{{margin:5px 0 10px}}
    .meta,.notice{{color:#566170}} .assessment{{border-left:4px solid #2f6f52;padding:10px 14px;background:#f2f7f4}}
    .limitations{{border-left:4px solid #b37a16;padding:8px 14px;background:#fff9ed}}
    table{{border-collapse:collapse;width:100%;table-layout:fixed}} td,th{{border-bottom:1px solid #d9dee5;padding:7px;text-align:left;vertical-align:top;overflow-wrap:anywhere}}
    th{{background:#eef1f4}} th:nth-child(1){{width:24%}} th:nth-child(2){{width:18%}}
    .FOUND .verdict{{color:#23633f}} .UNCERTAIN .verdict,.UNVERIFIABLE .verdict{{color:#8a5d0a}}
    small{{color:#626e7c}} code{{font-size:10px}} details{{margin-top:18px}}
    </style></head><body>
    <header><h1>Specter investigation report</h1>
    <p class='meta'>Generated {datetime.now(timezone.utc).isoformat()} · Specter {html.escape(str(stamp['tool_version']))}</p></header>
    <section><h2>Executive assessment</h2><div class='assessment'><b>{html.escape(str(profile.get('status', 'Unresolved')).replace('_', ' ').title())}</b>
    <p>{html.escape(str(assessment))}</p></div></section>
    {_profile_html(profile)}
    <section><h2>Observed evidence</h2>
    <p>{len(observed)} positive observation(s). A positive observation is not, by itself, proof of identity ownership.</p>
    <table><tr><th>Source observation</th><th>Classification</th><th>Reason and provenance</th></tr>{_finding_rows(observed)}</table></section>
    <section><h2>Needs review</h2>
    <p>{len(review)} uncertain or unavailable result(s).</p>
    <table><tr><th>Source observation</th><th>Classification</th><th>Reason and provenance</th></tr>{_finding_rows(review)}</table></section>
    <section><h2>Coverage and limitations</h2><div class='limitations'><ul>{limitations or '<li>No additional limitation was recorded.</li>'}</ul>
    <p>{absent} check(s) did not observe a match; {failed} check(s) failed. “Not observed” does not prove absence outside the checked source and time.</p></div></section>
    <details><summary>Technical audit details</summary><p><b>Authorized query:</b> <code>{query_json}</code></p>
    <p><b>Dataset receipt:</b> <code>{html.escape(str(stamp['sites_dataset_sha256']))}</code><br>
    <b>Evidence model:</b> {html.escape(str(stamp['evidence_model']['version']))}<br>
    <b>Scope:</b> {html.escape(str(stamp['engine']['scope_mode']))}; maximum depth {stamp['engine']['max_depth']}; passive only: {stamp['engine']['passive_only']}</p></details>
    <p class='notice'><small>{disclaimer}</small></p>
    </body></html>"""


def entity_report(run_id: int) -> dict:
    """Entity-centric report for a stored run: identities, their corroborating
    observations (with provenance), and changes since the prior run."""
    from .store import get_db, repo
    from .store import models_db as m

    db = get_db()
    with db.session() as s:
        run = s.get(m.Run, run_id)
        if not run:
            raise ValueError(f"no such run: {run_id}")
        target = s.get(m.Target, run.target_id)
        query = Query.model_validate(target.query)
        entities = repo.list_entities(s, run.target_id)
        changes = repo.list_changes(s, target_id=run.target_id)
        contradictions = repo.contradictions_for_target(s, run.target_id)
        from .provenance import provenance

        return {
            "tool": "Specter",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "provenance": provenance(),
            "run_id": run_id,
            "target": {"id": target.id, "label": target.label, "query": target.query},
            "disclaimer": DISCLAIMER,
            "profile": (run.stats or {}).get("profile"),
            "identities": [
                {
                    "id": e.id,
                    "label": e.label,
                    "confidence": e.confidence,
                    "flags": e.flags,
                    "attributes": e.attributes,
                    "evidence": [
                        {
                            "source": o.source,
                            "label": o.label,
                            "url": o.url,
                            "verdict": o.verdict,
                            "confidence": o.confidence,
                            "reliability": o.reliability,
                            "reasons": o.reasons,
                            "origin": o.origin,
                            "evidence_class": o.evidence_class,
                            "independence_key": o.independence_key,
                            "extractions": o.extractions or [],
                            "confidence_dimensions": o.confidence_dimensions,
                            "trace": o.trace,
                            "policy": o.policy,
                            "claim_key": o.claim_key,
                            "temporal_status": o.temporal_status,
                            "observed_at": o.observed_at.isoformat() if o.observed_at else None,
                            "first_seen_at": (
                                o.first_seen_at.isoformat() if o.first_seen_at else None
                            ),
                            "last_seen_at": o.last_seen_at.isoformat() if o.last_seen_at else None,
                            "completeness": o.completeness,
                        }
                        for o in e.observations
                        if confirmation_satisfied(o, e.observations, query)
                    ],
                }
                for e in entities
            ],
            "changes": [
                {
                    "kind": c.kind,
                    "source": c.source,
                    "label": c.label,
                    "detail": c.detail,
                    "at": c.created_at.isoformat(),
                }
                for c in changes
            ],
            "contradictions": [
                {
                    "id": c.id,
                    "claim_key": c.claim_key,
                    "earlier_observation_id": c.earlier_observation_id,
                    "later_observation_id": c.later_observation_id,
                    "kind": c.kind,
                    "severity": c.severity,
                    "reasons": c.reasons,
                    "at": c.created_at.isoformat(),
                }
                for c in contradictions
            ],
        }


def save(query, findings, summary, fmt: str, out: str | None = None) -> Path:
    reports = Path(SETTINGS.reports_dir)
    reports.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    path = Path(out) if out else reports / f"specter-{stamp}.{fmt}"

    if fmt == "json":
        path.write_text(to_json(query, findings, summary), encoding="utf-8")
    elif fmt == "csv":
        path.write_text(to_csv(findings), encoding="utf-8")
    elif fmt == "pdf":
        html = to_pdf_html(query, findings, summary)
        try:
            from weasyprint import HTML  # optional dependency

            HTML(string=html).write_pdf(str(path))
        except Exception:
            path = path.with_suffix(".html")
            path.write_text(html, encoding="utf-8")
    else:
        raise ValueError(f"unknown format: {fmt}")
    return path
